ifeq ($(PREFIX),)
	PREFIX := /usr/local
endif

.PHONY: build
build:
	go build -o {{.Name}} .

.PHONY: clean
clean:
	rm -f {{.Name}}

.PHONY: dev
dev:
	go run main.go

PHONY: test
test:
	go test ./...
